import getCurrentDatetime from "../utils/getCurrentDatetime";
export const simulateData = [
	{
		id: "1",
		controlAttributeName: "Creation Of dummy",
		reportName: "AD_U_GL_Accounts",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: false,
		simulateAt: "",
		simulatedBy: "",
	},
	{
		id: "2",
		controlAttributeName: "Creation 2nd attribute",
		reportName: "AD_2nd_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: false,
		simulateAt: "",
		simulatedBy: "",
	},
	{
		id: "3",
		controlAttributeName: "Creation 3rd attribute",
		reportName: "AD_3rd_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: false,
		simulateAt: "",
		simulatedBy: "",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
	{
		id: "4",
		controlAttributeName: "Creation 4th attribute",
		reportName: "AD_4th_Report",
		syncAt: getCurrentDatetime(),
		syncedBy: "Suman Mondal",
		isSimulated: true,
		simulateAt: getCurrentDatetime(),
		simulatedBy: "Suman Mondal",
	},
];
